language: r
cache: packages
sudo: required
dist: trusty

r_packages:
 - reticulate
 - googledrive


addons:
  apt:
    sources:
     - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'



before_install:
 - sudo apt-get update
 - sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev 
 - R -q -e 'install.packages("sf")'

 - wget https://repo.anaconda.com/archive/Anaconda3-5.2.0-Linux-x86_64.sh -O anaconda.sh
 - bash anaconda.sh -b -p $HOME/anaconda
 - export PATH="$HOME/anaconda/bin:$PATH"
 - hash -r
 - conda config --set always_yes yes --set changeps1 no

after_success:

- R -q -e 'earthEngineGrabR::ee_grab_install()'

