language: r
cache: packages
sudo: required
dist: trusty

r_packages:
 - reticulate
 - googledrive



addons:
  apt:
    sources:
     - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'



before_install:
 - sudo apt-get update
 - sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev 


 - wget https://repo.anaconda.com/archive/Anaconda3-5.2.0-Linux-x86_64.sh -O anaconda.sh
 - bash anaconda.sh -b -p $HOME/anaconda
 - export PATH="$HOME/anaconda/bin:$PATH"
 - hash -r
 - conda config --set always_yes yes --set changeps1 no

 - mkdir /home/.config
 - mkdir /home/.config/earthengine
 - mv -v tests/testthat/test-tokens/* /home/.config/earthengine

install:
 - Rscript -e 'install.packages("sf")'
 - Rscript -e 'install.packages("googledrive")'
 - Rscript -e 'install.packages("reticulate")'
 - Rscript -e 'install.packages("testthat")'

before_script:
 - R CMD INSTALL .
 - R -e 'earthEngineGrabR::ee_grab_install(clean_credentials = F)'
 - R -e 'library(sf)'


