# DO NOT CHANGE the "init" and "install" sections below
image: Visual Studio 2015

environment:
  NOT_CRAN: true
  USE_RTOOLS: true


# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap






# Adapt as necessary starting from here


build_script:
  - R CMD INSTALL .
  - travis-tool.sh install_github hadley/devtools
  - travis-tool.sh install_deps
#  - travis-tool.sh install_r sf

  - mkdir C:\Users\appveyor\Documents\.config\earthengine
  - move tests\testthat\test-tokens\* C:\Users\appveyor\Documents\.config\earthengine
  - R CMD INSTALL .
  - R -e 'earthEngineGrabR::ee_grab_install(clean_credentials=F)'

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
